{
 "title": "Infinispan Monitoring",
 "time": { "from": "2025-02-07T13:57:32.945Z", "to": "2025-02-07T19:50:16.913Z" },
 "panels": [
  {
   "title": "TEST2 Cache no. Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_test2_statistics_approximate_entries",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Cache no. Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_test_statistics_approximate_entries",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserimenti nella Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_stores",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "base_cpu_processCpuLoad", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Read/Write time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_average_read_time_nanos",
     "legendFormat": "__auto"
    },
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_average_write_time_nanos",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}