global:
  scrape_interval: 2s  # Frequenza di raccolta delle metriche

scrape_configs:
  - job_name: 'jaeger'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: 'infinispan'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['infinispan-tracing:11222']
    basic_auth:
      username: "admin"
      password: "password"
