global:
  scrape_interval: 2s  # Ogni 5 secondi raccoglie le metriche

scrape_configs:
  - job_name: 'jaeger'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:14269']  # Endpoint da cui raccogliere metriche
